/**
 * PracticePage — Page Object Model for the GTO Wizard Practice page
 * 
 * Uses stable button text selectors and section visibility for state detection
 * (the Practice page doesn't use aria-pressed attributes).
 * Compatible with @playwright/test — pass the Playwright Page to constructor.
 * 
 * Generated by Coach test-generator on 2026-06-24, hardened via Phase 4 VERIFY.
 * 
 * Usage:
 *   const pom = new PracticePage(page);
 *   await pom.navigate();
 *   await pom.selectExerciseType('Timed Drill');
 *   const result = await pom.startSession();
 */

import type { Page } from '@playwright/test';

// ── Types ──────────────────────────────────────────────────────

export type ExerciseType = 'GTO Quiz' | 'Timed Drill' | 'Spaced Repetition';
export type TimerDuration = '30s' | '60s' | '120s';
export type Category = 'All' | '3-bet pot' | 'Open-raise pot' | 'Overcard board' | 'Monoboard' | 'Paired board' | 'Wet board';
export type Difficulty = 'All' | 'Beginner' | 'Intermediate' | 'Advanced';

export interface SpacedRepetitionStats {
  tracked: number;
  due: number;
}

export interface PracticeSessionResult {
  url: string;
  sessionOverlayVisible: boolean;
  hasGTOQuestion: boolean;
  apiError: string | null;
  sessionStats: {
    spots: number;
    accuracy: number;
    streak: number;
    time: string;
  } | null;
  consoleErrors: string[];
}

// ── POM Class ──────────────────────────────────────────────────

export class PracticePage {
  constructor(private page: Page) {}

  // ── Navigation ──────────────────────────────────────────────

  async navigate(): Promise<void> {
    await this.page.goto('/practice');
    await this.page.waitForLoadState('networkidle');
  }

  // ── State Queries ───────────────────────────────────────────

  async getActiveExerciseType(): Promise<ExerciseType> {
    // Check for conditional section visibility instead of aria-pressed
    const bodyText = await this.page.evaluate(() => document.body.innerText);
    const hasTimerSection = bodyText.includes('Timer Duration') || bodyText.includes('30s');
    const hasSpacedSection = bodyText.includes('spots tracked') || bodyText.includes('due for review');
    if (hasTimerSection) return 'Timed Drill';
    if (hasSpacedSection) return 'Spaced Repetition';
    return 'GTO Quiz';
  }

  async getActiveCategory(): Promise<Category> {
    return 'All'; // fallback — CSS class based, see catalog notes
  }

  async getActiveDifficulty(): Promise<Difficulty> {
    return 'All';
  }

  async getTimerDuration(): Promise<TimerDuration | null> {
    const activeType = await this.getActiveExerciseType();
    if (activeType !== 'Timed Drill') return null;
    return await this.page.evaluate(() => {
      const timerBtns = Array.from(document.querySelectorAll('button'))
        .filter(b => b.textContent?.match(/^30s$|^60s$|^120s$/));
      const active = timerBtns.find(b => b.className.includes('bg-') && !b.className.includes('bg-gray'));
      return (active?.textContent?.trim() as TimerDuration) || '60s';
    });
  }

  async getSpacedRepetitionStats(): Promise<SpacedRepetitionStats | null> {
    const activeType = await this.getActiveExerciseType();
    if (activeType !== 'Spaced Repetition') return null;
    return await this.page.evaluate(() => {
      const text = document.body.innerText;
      const match = text.match(/(\d+)\s+spots tracked\s*·\s*(\d+)\s+due/);
      if (!match) return null;
      return { tracked: parseInt(match[1]), due: parseInt(match[2]) };
    });
  }

  // ── State Mutations ─────────────────────────────────────────

  async selectExerciseType(type: ExerciseType): Promise<void> {
    await this.page.getByRole('button', { name: type }).click();
    // Wait for the conditional section to appear (React re-render)
    if (type === 'Timed Drill') {
      await this.page.waitForSelector('text=Timer Duration', { state: 'visible', timeout: 5000 });
    } else if (type === 'Spaced Repetition') {
      await this.page.waitForSelector('text=spots tracked', { state: 'visible', timeout: 5000 });
    }
    // GTO Quiz is the default — no conditional section to wait for
  }

  async selectTimerDuration(duration: TimerDuration): Promise<void> {
    const activeType = await this.getActiveExerciseType();
    if (activeType !== 'Timed Drill') {
      await this.selectExerciseType('Timed Drill');
    }
    await this.page.getByRole('button', { name: duration }).click();
    await this.page.waitForTimeout(300);
  }

  async selectCategory(category: Category): Promise<void> {
    await this.page.getByRole('button', { name: category }).click();
    await this.page.waitForTimeout(300);
  }

  async selectDifficulty(difficulty: Difficulty): Promise<void> {
    await this.page.getByRole('button', { name: difficulty }).click();
    await this.page.waitForTimeout(300);
  }

  async startSession(): Promise<PracticeSessionResult> {
    await this.page.getByRole('button', { name: 'Start Practice Session' }).click();
    // Wait for the quiz question to load (API call + render)
    await this.page.waitForTimeout(5000);

    const url = this.page.url();
    const bodyText = await this.page.evaluate(() => document.body.innerText);
    const errors = this.page.isClosed() ? [] : await this.page.evaluate(() => {
      return (window as any).__errors || [];
    });

    const overlayVisible = bodyText.includes('End Session');
    const hasGTOQuestion = bodyText.includes('?') &&
      (bodyText.includes('GTO') || bodyText.includes('Quiz') || bodyText.includes('Spot'));
    const apiError = bodyText.includes('Unable to load training spot')
      ? 'Quiz API not responding — the backend quiz endpoint is unreachable'
      : null;

    let sessionStats: PracticeSessionResult['sessionStats'] = null;
    const statsMatch = bodyText.match(/Spots:\s*(\d+)\s*Accuracy:\s*(\d+)%\s*Streak:\s*(\d+)\s*Time:\s*([\d:]+)/);
    if (statsMatch) {
      sessionStats = {
        spots: parseInt(statsMatch[1]),
        accuracy: parseInt(statsMatch[2]),
        streak: parseInt(statsMatch[3]),
        time: statsMatch[4]
      };
    }

    return { url, sessionOverlayVisible: overlayVisible, hasGTOQuestion, apiError, sessionStats, consoleErrors: errors };
  }

  // ── Assertions ──────────────────────────────────────────────

  async assertExerciseTypeChangesTo(type: ExerciseType): Promise<void> {
    const current = await this.getActiveExerciseType();
    if (current !== type) {
      throw new Error(`Expected exercise type "${type}", got "${current}".`);
    }
  }

  async assertTimerDurationVisible(): Promise<void> {
    const type = await this.getActiveExerciseType();
    if (type !== 'Timed Drill') {
      throw new Error(`Timer Duration should only be visible in Timed Drill mode. Current mode: ${type}`);
    }
  }

  async assertTimerDurationHidden(): Promise<void> {
    const type = await this.getActiveExerciseType();
    if (type === 'Timed Drill') {
      throw new Error('Timer Duration section should be hidden but Timed Drill is active');
    }
  }

  async assertSpacedRepetitionStatsVisible(): Promise<void> {
    const type = await this.getActiveExerciseType();
    if (type !== 'Spaced Repetition') {
      throw new Error(`Spaced Repetition stats should only be visible in Spaced Repetition mode. Current mode: ${type}`);
    }
    const stats = await this.getSpacedRepetitionStats();
    if (!stats) {
      throw new Error('Spaced Repetition section visible but stats could not be parsed');
    }
  }

  async assertSessionStarted(result: PracticeSessionResult): Promise<void> {
    if (!result.sessionOverlayVisible) {
      throw new Error(`Session did not start. No overlay detected. URL: ${result.url}.`);
    }
    if (result.apiError) {
      console.warn(`⚠️ Finding: ${result.apiError}`);
      return;
    }
    if (!result.hasGTOQuestion) {
      throw new Error(`Session started but no GTO question found. Stats: ${JSON.stringify(result.sessionStats)}`);
    }
    if (result.consoleErrors.length > 0) {
      throw new Error(`Console errors: ${result.consoleErrors.join('; ')}`);
    }
  }

  async assertNoConsoleErrors(): Promise<void> {
    const errors = await this.page.evaluate(() => (window as any).__errors || []);
    if (errors.length > 0) {
      throw new Error(`Console errors found: ${errors.join('; ')}`);
    }
  }
}
