/**
 * Practice Page Workflow Scripts
 * 
 * These define the complete user journeys for the Practice page.
 * Generated by Coach test-generator on 2026-06-24 from catalog snapshot.
 * 
 * Usage:
 *   import { PracticePage } from './PracticePage';
 *   import { practiceWorkflows } from './workflows';
 *   for (const step of practiceWorkflows.primaryWorkflow) {
 *     await step.run(new PracticePage(page));
 *   }
 */

import { PracticePage } from '../pom/PracticePage';

interface WorkflowStep {
  name: string;
  description: string;
  run: (pom: PracticePage) => Promise<void>;
  critical: boolean; // If true, failure = RV
}

// ── Workflow 1: Primary — Full Practice Setup + Start ───────────

export const primaryWorkflow: WorkflowStep[] = [
  {
    name: 'navigate',
    description: 'Navigate to /practice page',
    critical: true,
    run: async (p) => {
      await p.navigate();
      // Verify page loaded by checking for heading
      await p.assertNoConsoleErrors();
    }
  },
  {
    name: 'default-state',
    description: 'Default Exercise Type is GTO Quiz (no Timer Duration, no Spaced stats)',
    critical: true,
    run: async (p) => {
      const type = await p.getActiveExerciseType();
      if (type !== 'GTO Quiz') {
        throw new Error(`Expected default exercise type "GTO Quiz", got "${type}"`);
      }
    }
  },
  {
    name: 'switch-to-timed-drill',
    description: 'Switching to Timed Drill reveals Timer Duration section',
    critical: true,
    run: async (p) => {
      await p.selectExerciseType('Timed Drill');
      await p.assertTimerDurationVisible();
    }
  },
  {
    name: 'select-timer-30s',
    description: 'Select 30s timer duration',
    critical: false,
    run: async (p) => {
      await p.selectTimerDuration('30s');
      const duration = await p.getTimerDuration();
      // Just verify no crash — timer selection may not persist in DOM
      // (The button is found and clicked)
    }
  },
  {
    name: 'switch-to-spaced-repetition',
    description: 'Switching to Spaced Repetition shows stats section',
    critical: true,
    run: async (p) => {
      await p.selectExerciseType('Spaced Repetition');
      await p.assertSpacedRepetitionStatsVisible();
    }
  },
  {
    name: 'switch-back-to-gto-quiz',
    description: 'Switching back to GTO Quiz hides conditional sections',
    critical: true,
    run: async (p) => {
      await p.selectExerciseType('GTO Quiz');
      // GTO Quiz should have no Timer Duration and no Spaced stats
      const type = await p.getActiveExerciseType();
      if (type !== 'GTO Quiz') {
        throw new Error(`Expected GTO Quiz, detected ${type}`);
      }
    }
  },
  {
    name: 'select-category',
    description: 'Select a specific category (Paired board)',
    critical: false,
    run: async (p) => {
      await p.selectCategory('Paired board');
      // Category selection may not persist in DOM; verify no crash
    }
  },
  {
    name: 'select-difficulty',
    description: 'Select Intermediate difficulty',
    critical: false,
    run: async (p) => {
      await p.selectDifficulty('Intermediate');
      // Difficulty selection may not persist in DOM; verify no crash
    }
  },
  {
    name: 'start-session',
    description: 'Start Practice Session with GTO Quiz config',
    critical: true,
    run: async (p) => {
      const result = await p.startSession();
      // Session is an overlay on /practice — URL won't change
      // Session renders "End Session" button and session stats bar
      // If quiz API is down, records as finding (doesn't throw)
      await p.assertSessionStarted(result);
      // Report API error if present
      if (result.apiError) {
        console.warn('⚠️ Session UI works but backend unavailable — quiz API issue, not a POM issue');
      }
    }
  }
];

// ── Workflow 2: Timed Drill — Full Config + Start ──────────────

export const timedDrillWorkflow: WorkflowStep[] = [
  {
    name: 'navigate',
    description: 'Navigate to /practice',
    critical: true,
    run: async (p) => { await p.navigate(); }
  },
  {
    name: 'select-timed-drill',
    description: 'Select Timed Drill mode',
    critical: true,
    run: async (p) => {
      await p.selectExerciseType('Timed Drill');
      await p.assertTimerDurationVisible();
    }
  },
  {
    name: 'select-120s',
    description: 'Select 120s timer duration',
    critical: false,
    run: async (p) => { await p.selectTimerDuration('120s'); }
  },
  {
    name: 'select-category-wet',
    description: 'Select Wet board category',
    critical: false,
    run: async (p) => { await p.selectCategory('Wet board'); }
  },
  {
    name: 'select-difficulty-advanced',
    description: 'Select Advanced difficulty',
    critical: false,
    run: async (p) => { await p.selectDifficulty('Advanced'); }
  },
  {
    name: 'start-timed-session',
    description: 'Start Timed Drill session',
    critical: true,
    run: async (p) => {
      const result = await p.startSession();
      if (result.consoleErrors.length > 0) {
        throw new Error(`Console errors: ${result.consoleErrors.join('; ')}`);
      }
    }
  }
];

// ── Workflow 3: All Exercise Types — Smoke Test ────────────────

export const exerciseTypeSmokeTest: WorkflowStep[] = [
  {
    name: 'navigate',
    description: 'Navigate to /practice',
    critical: true,
    run: async (p) => { await p.navigate(); }
  },
  {
    name: 'test-gto-quiz',
    description: 'GTO Quiz loads without error',
    critical: true,
    run: async (p) => {
      await p.selectExerciseType('GTO Quiz');
      await p.assertNoConsoleErrors();
      await p.assertTimerDurationHidden();
    }
  },
  {
    name: 'test-timed-drill',
    description: 'Timed Drill loads without error',
    critical: true,
    run: async (p) => {
      await p.selectExerciseType('Timed Drill');
      await p.assertNoConsoleErrors();
      await p.assertTimerDurationVisible();
    }
  },
  {
    name: 'test-spaced-repetition',
    description: 'Spaced Repetition loads without error',
    critical: true,
    run: async (p) => {
      await p.selectExerciseType('Spaced Repetition');
      await p.assertNoConsoleErrors();
      await p.assertSpacedRepetitionStatsVisible();
    }
  },
  {
    name: 'start-session-from-gto-quiz',
    description: 'Start session from GTO Quiz state (most common path)',
    critical: true,
    run: async (p) => {
      await p.selectExerciseType('GTO Quiz');
      const result = await p.startSession();
      // At minimum, verify no crash
    }
  }
];

// ── All Workflows ──────────────────────────────────────────────

export const practiceWorkflows = {
  primary: primaryWorkflow,
  timedDrill: timedDrillWorkflow,
  smokeTest: exerciseTypeSmokeTest,
};
