// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/analyze" | "/analyze/hands" | "/analyze/leaks" | "/analyze/viewer" | "/bomb-pot" | "/courses" | "/courses/[id]" | "/double-board" | "/equity" | "/equity/2-7sd" | "/equity/2-7td" | "/equity/badugi" | "/equity/omaha" | "/equity/plo" | "/equity/plo4" | "/equity/plo5" | "/equity/razz" | "/equity/stud" | "/equity/stud8" | "/hand-history" | "/icm" | "/leaderboard" | "/omaha" | "/play" | "/plo" | "/plo4" | "/practice" | "/progress" | "/push-fold" | "/quiz" | "/range-explorer" | "/solutions" | "/spots" | "/strategies" | "/strategy" | "/study" | "/train" | "/train/review" | "/trainer" | "/variants"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]" | "/bomb-pot/[[...path]]" | "/double-board/[[...path]]" | "/icm/[[...path]]" | "/omaha/[[...path]]" | "/plo4/[[...path]]" | "/ws/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/analyze": {}
  "/analyze/hands": {}
  "/analyze/leaks": {}
  "/analyze/viewer": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/bomb-pot": {}
  "/bomb-pot/[[...path]]": { "path"?: string[]; }
  "/courses": {}
  "/courses/[id]": { "id": string; }
  "/double-board": {}
  "/double-board/[[...path]]": { "path"?: string[]; }
  "/equity": {}
  "/equity/2-7sd": {}
  "/equity/2-7td": {}
  "/equity/badugi": {}
  "/equity/omaha": {}
  "/equity/plo": {}
  "/equity/plo4": {}
  "/equity/plo5": {}
  "/equity/razz": {}
  "/equity/stud": {}
  "/equity/stud8": {}
  "/hand-history": {}
  "/icm": {}
  "/icm/[[...path]]": { "path"?: string[]; }
  "/leaderboard": {}
  "/omaha": {}
  "/omaha/[[...path]]": { "path"?: string[]; }
  "/play": {}
  "/plo": {}
  "/plo4": {}
  "/plo4/[[...path]]": { "path"?: string[]; }
  "/practice": {}
  "/progress": {}
  "/push-fold": {}
  "/quiz": {}
  "/range-explorer": {}
  "/solutions": {}
  "/spots": {}
  "/strategies": {}
  "/strategy": {}
  "/study": {}
  "/train": {}
  "/train/review": {}
  "/trainer": {}
  "/variants": {}
  "/ws/[[...path]]": { "path"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
