// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/analyze/hands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analyze/hands">> = Specific
  const handler = {} as typeof import("../../src/app/analyze/hands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/analyze/leaks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analyze/leaks">> = Specific
  const handler = {} as typeof import("../../src/app/analyze/leaks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/analyze/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analyze">> = Specific
  const handler = {} as typeof import("../../src/app/analyze/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/analyze/viewer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analyze/viewer">> = Specific
  const handler = {} as typeof import("../../src/app/analyze/viewer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/bomb-pot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bomb-pot">> = Specific
  const handler = {} as typeof import("../../src/app/bomb-pot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/courses/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/courses/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/courses/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/courses">> = Specific
  const handler = {} as typeof import("../../src/app/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/double-board/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/double-board">> = Specific
  const handler = {} as typeof import("../../src/app/double-board/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/equity/2-7sd/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equity/2-7sd">> = Specific
  const handler = {} as typeof import("../../src/app/equity/2-7sd/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/equity/2-7td/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equity/2-7td">> = Specific
  const handler = {} as typeof import("../../src/app/equity/2-7td/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/equity/badugi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equity/badugi">> = Specific
  const handler = {} as typeof import("../../src/app/equity/badugi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/equity/omaha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equity/omaha">> = Specific
  const handler = {} as typeof import("../../src/app/equity/omaha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/equity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equity">> = Specific
  const handler = {} as typeof import("../../src/app/equity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/equity/plo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equity/plo">> = Specific
  const handler = {} as typeof import("../../src/app/equity/plo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/equity/plo4/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equity/plo4">> = Specific
  const handler = {} as typeof import("../../src/app/equity/plo4/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/equity/plo5/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equity/plo5">> = Specific
  const handler = {} as typeof import("../../src/app/equity/plo5/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/equity/razz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equity/razz">> = Specific
  const handler = {} as typeof import("../../src/app/equity/razz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/equity/stud/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equity/stud">> = Specific
  const handler = {} as typeof import("../../src/app/equity/stud/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/equity/stud8/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equity/stud8">> = Specific
  const handler = {} as typeof import("../../src/app/equity/stud8/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hand-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hand-history">> = Specific
  const handler = {} as typeof import("../../src/app/hand-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/icm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/icm">> = Specific
  const handler = {} as typeof import("../../src/app/icm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/omaha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/omaha">> = Specific
  const handler = {} as typeof import("../../src/app/omaha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/play/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/play">> = Specific
  const handler = {} as typeof import("../../src/app/play/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/plo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plo">> = Specific
  const handler = {} as typeof import("../../src/app/plo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/plo4/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plo4">> = Specific
  const handler = {} as typeof import("../../src/app/plo4/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/practice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practice">> = Specific
  const handler = {} as typeof import("../../src/app/practice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/progress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/progress">> = Specific
  const handler = {} as typeof import("../../src/app/progress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/push-fold/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/push-fold">> = Specific
  const handler = {} as typeof import("../../src/app/push-fold/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/quiz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quiz">> = Specific
  const handler = {} as typeof import("../../src/app/quiz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/range-explorer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/range-explorer">> = Specific
  const handler = {} as typeof import("../../src/app/range-explorer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/spots/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/spots">> = Specific
  const handler = {} as typeof import("../../src/app/spots/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/strategies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/strategies">> = Specific
  const handler = {} as typeof import("../../src/app/strategies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/strategy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/strategy">> = Specific
  const handler = {} as typeof import("../../src/app/strategy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/study/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/study">> = Specific
  const handler = {} as typeof import("../../src/app/study/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/train/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/train">> = Specific
  const handler = {} as typeof import("../../src/app/train/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/train/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/train/review">> = Specific
  const handler = {} as typeof import("../../src/app/train/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/trainer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trainer">> = Specific
  const handler = {} as typeof import("../../src/app/trainer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/variants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/variants">> = Specific
  const handler = {} as typeof import("../../src/app/variants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
